# Generated by Django 5.0.1 on 2024-09-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_details', '0028_alter_storeopening_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='en_name',
            field=models.CharField(default=1, max_length=255, verbose_name='اسم المنتج'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='en_name',
            field=models.CharField(default=1, max_length=255, verbose_name='اسم المنتج'),
            preserve_default=False,
        ),
    ]
