# Generated by Django 5.0.1 on 2024-09-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_details', '0029_product_en_name_service_en_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='en_name',
            field=models.CharField(max_length=255, verbose_name='اسم المنتج بالإنكليزية'),
        ),
        migrations.AlterField(
            model_name='service',
            name='en_name',
            field=models.CharField(max_length=255, verbose_name='اسم الخدمة بالإنكليزية'),
        ),
    ]
