# Generated by Django 5.0.1 on 2024-09-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_details', '0030_alter_product_en_name_alter_service_en_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='en_name',
            field=models.CharField(default=1, max_length=255, verbose_name='اسم المتجر بالإنكليزية'),
            preserve_default=False,
        ),
    ]
