# Generated by Django 5.0.1 on 2024-09-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Congig',
            new_name='Config',
        ),
    ]
