# Generated by Django 5.0.1 on 2024-09-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0028_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
