# Generated by Django 5.0.1 on 2024-09-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categroy', '0002_alter_category_created_at_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='en_name',
            field=models.CharField(default=1, max_length=255, verbose_name='اسم التصنيف بالإنكليزية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainservice',
            name='en_name',
            field=models.CharField(default=1, max_length=255, verbose_name='اسم الخدمة بالإنكليزية'),
            preserve_default=False,
        ),
    ]
